# Generated by Django 5.1.5 on 2025-01-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pais', models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brasil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'México'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PR', 'Puerto Rico'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('US', 'Estados Unidos'), ('ES', 'España')], max_length=2)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
